services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4001:4001'
