import { FeatherPlay, FeatherRepeat } from '@ng-icons/feather-icons';
import {
  HeroArrowLeft,
  HeroBell,
  HeroBookmark,
  HeroCalendar,
  HeroChartBar,
  HeroChat,
  HeroChevronDown,
  HeroClipboardList,
  HeroDotsCircleHorizontal,
  HeroDotsHorizontal,
  HeroEmojiHappy,
  HeroHashtag,
  HeroHeart,
  HeroHome,
  HeroInbox,
  HeroPhotograph,
  HeroShare,
  HeroSparkles,
  HeroUser,
  HeroX,
} from '@ng-icons/heroicons/outline';
import { HeroHeartSolid } from '@ng-icons/heroicons/solid';
export const HeroIconsImportList = {
  HeroHashtag,
  HeroHome,
  HeroBell,
  HeroInbox,
  HeroBookmark,
  HeroClipboardList,
  HeroUser,
  HeroDotsCircleHorizontal,
  HeroDotsHorizontal,
  HeroSparkles,
  HeroPhotograph,
  HeroEmojiHappy,
  HeroCalendar,
  HeroChartBar,
  HeroX,
  HeroShare,
  HeroHeart,
  HeroHeartSolid,
  HeroChat,
  HeroChevronDown,
  FeatherRepeat,
  FeatherPlay,
  HeroArrowLeft,
};
